name: dai-labo-3

networks:
  network:
    name: network

services:
  emitter:
    image: ghcr.io/alexandrephilibert/smt:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    command:
      - emitter
      - --host=239.0.192.5
      - --interface=eth0

  receiver:
    image: ghcr.io/alexandrephilibert/smt:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    command:
      - receiver

  server:
    image: ghcr.io/alexandrephilibert/smt:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    command:
      - server
      - --host=239.0.192.5
      - --interface=eth0
