name: dai-labo-3

networks:
  network:
    name: network

services:
  public-emitter:
    image: ghcr.io/alexandrephilibert/smt:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    command:
      - emitter
      - --interface=eth0

  private-emitter:
    image: ghcr.io/alexandrephilibert/smt:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    command:
      - emitter
      - --interface=eth0
      - --private

  receiver:
    image: ghcr.io/alexandrephilibert/smt:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    command:
      - receiver

  server:
    image: ghcr.io/alexandrephilibert/smt:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    command:
      - server
      - --interface=eth0
