name: dai-labo-3

networks:
  network:
    name: network

services:
  public-emitter:
    image: ghcr.io/alexandrephilibert/smt:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    command:
      - emitter
      - --interface=eth0
      - --name=bingo-nameo

  private-emitter:
    image: ghcr.io/alexandrephilibert/smt:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    command:
      - emitter
      - --interface=eth0
      - --private
      - --name=papaya

  receiver:
    image: ghcr.io/alexandrephilibert/smt:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    command:
      - receiver

  server:
    image: ghcr.io/alexandrephilibert/smt:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 25592:25592/udp
    networks:
      - network
    command:
      - server
      - --interface=eth0
